name: Manual Test Build

on:
  workflow_dispatch:
    branches: [master]

jobs:
  linux-build:
    name: Linux Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: PDM
        run: python3.12 -m pip install pdm

      - name: Install libkrb5-dev
        run: sudo apt-get install -y libkrb5-dev

      - name: Installs dev deps and package
        run : PDM_BUILD_SCM_VERSION=$(cat VERSION) pdm install --dev

      - name: Build binary release
        run: |
          pdm run python3.12 -m nuitka --standalone --onefile --output-filename=ldeep.bin ldeep/__main__.py
          mv ldeep.bin ldeep_linux-amd64

      - name: Build Source Distribution
        run: PDM_BUILD_SCM_VERSION=$(cat VERSION) pdm build -d sdist --no-wheel

      - name: Upload Artifacts (binary)
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ldeep_linux-amd64

      - name: Upload Artifacts (sdist)
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: sdist/*

  windows-build:
    name: Windows Build
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: PDM
        run: python3 -m pip install pdm

      - name: Installs dev deps and package
        run: $env:PDM_BUILD_SCM_VERSION=gc "VERSION"; pdm install --dev

      - name: Build
        run: |
          pdm run python3 -m nuitka --standalone --assume-yes-for-downloads --output-filename=ldeep.exe --onefile ldeep/__main__.py
          mv ldeep.exe ldeep_windows-amd64.exe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ldeep_windows-amd64.exe

  macos-build:
    name: MacOS ARM64 Build
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: PDM
        run: python3.12 -m pip install pdm

      - name: Installs dev deps and package
        run: PDM_BUILD_SCM_VERSION=$(cat VERSION) pdm install --dev

      - name: Build
        run: |
          pdm run python3.12 -m nuitka --standalone --onefile --output-filename=ldeep.bin ldeep/__main__.py
          mv ldeep.bin ldeep_macos-arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: ldeep_macos-arm64

  macos-amd-build:
    name: MacOS AMD64 Build
    runs-on: "macos-13"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: PDM
        run: python3.12 -m pip install pdm

      - name: Installs dev deps and package
        run: PDM_BUILD_SCM_VERSION=$(cat VERSION) pdm install --dev

      - name: Build
        run: |
          pdm run python3.12 -m nuitka --standalone --onefile --output-filename=ldeep.bin ldeep/__main__.py
          mv ldeep.bin ldeep_macos-amd64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd
          path: ldeep_macos-amd64
